/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/na2GsfJnj5h
 */
import { Projects } from "./projects"
import { Hero } from "./hero"
import Footer from "./footer"
import Contact from "./contact"
import Header from "./header"
import { Skills } from "./skills"

export function Index() {
  return (
    <div key="1" className="flex flex-col min-h-screen bg-gradient-to-r from-gray-100 to-gray-250">
      <Header />
      <main className="flex-1">
        <Hero />
        <Projects />
        <Skills />
        <Contact />
      </main>
      <Footer />
    </div>
  )
}
