/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PhjeGODULbM
 */
import { CardTitle, CardHeader, CardDescription, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Projects() {
  return (
    <section className="w-full py-12 md:py-24 bg-white flex justify-center">
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Projects</h2>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Here are some of the projects that I&apos;ve been working on.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 max-w-6xl w-full mx-auto">
          <Card>
            <CardHeader className="flex flex-row items-start justify-between">
              <div className="grid gap-1">
                <CardTitle>Supreme Cop Bot</CardTitle>
              </div>
              <Badge className="bg-gray-100 text-black">Favourite</Badge>
            </CardHeader>
            <CardContent className="grid gap-2">
              <CardDescription className="text-sm md:text-base lg:text-lg text-left">
                Supreme Bot is a web scraper for online shops. It bypasses bot protections, monitors restocks, and can auto-purchase items for users.
              </CardDescription>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-start justify-between">
              <div className="grid gap-1">
                <CardTitle>Solana dApp</CardTitle>
              </div>
              <Badge className="bg-gray-100 text-black">Currently in Progress</Badge>
            </CardHeader>
            <CardContent className="grid gap-2">
              <CardDescription className="text-sm md:text-base lg:text-lg text-left">
                This project is about learning Solana smart contract development and creating a dApp on the Solana blockchain.
              </CardDescription>
              <Button variant="link">
                <Link href="https://github.com/SebastianBoehler/solana-dapp-learning">View on GitHub</Link>
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}
