/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PhjeGODULbM
 */
import { CardTitle, CardHeader, CardDescription, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Projects() {
  return (
    <section className="w-full py-12 md:py-24 bg-white">
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Projects</h2>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Here are some of the projects that I&apos;ve been working on.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 max-w-6xl w-full mx-auto">
          <Card>
            <CardHeader className="flex flex-row items-start justify-between">
              <div className="grid gap-1">
                <CardTitle>Project 1</CardTitle>
              </div>
              <Badge className="bg-gray-100 text-black">My Favourite</Badge>
            </CardHeader>
            <CardContent className="grid gap-2">
              <CardDescription className="text-sm md:text-base lg:text-lg">
                This is a much more detailed and longer description of Project 1. Here, you can elaborate on the scope,
                goals, and outcome of the project.
              </CardDescription>
              <Button variant="link">
                <Link href="#">View on GitHub</Link>
              </Button>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-start justify-between">
              <div className="grid gap-1">
                <CardTitle>Project 2</CardTitle>
              </div>
              <Badge className="bg-gray-100 text-black">Currently in Progress</Badge>
            </CardHeader>
            <CardContent className="grid gap-2">
              <CardDescription className="text-sm md:text-base lg:text-lg">
                This is a much more detailed and longer description of Project 2. Here, you can elaborate on the scope,
                goals, and outcome of the project.
              </CardDescription>
              <Button variant="link">
                <Link href="#">View on GitHub</Link>
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}
