/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yO4AW7fs9eC
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function Skills() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10 mx-auto">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Skills</h2>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            These are the languages, tools, and frameworks I&apos;ve mastered over the years.
          </p>
        </div>
        <div className="grid w-full grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8 lg:gap-12">
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <CodeIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Coding Languages</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2">
              <Badge variant="secondary">Typescript</Badge>
              <Badge variant="secondary">JavaScript</Badge>
              <Badge variant="secondary">Rust</Badge>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <PenToolIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Tools</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2">
              <Badge variant="secondary">VS Code</Badge>
              <Badge variant="secondary">Git</Badge>
              <Badge variant="secondary">Docker</Badge>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <FrameIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Frameworks</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2">
              <Badge variant="secondary">React</Badge>
              <Badge variant="secondary">Express.js</Badge>
              <Badge variant="secondary">Next.JS</Badge>
              <Badge variant="secondary">Solana/web3.js</Badge>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}


function CodeIcon(props: Record<string, unknown>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function PenToolIcon(props: Record<string, unknown>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19 7-7 3 3-7 7-3-3z" />
      <path d="m18 13-1.5-7.5L2 2l3.5 14.5L13 18l5-5z" />
      <path d="m2 2 7.586 7.586" />
      <circle cx="11" cy="11" r="2" />
    </svg>
  )
}


function FrameIcon(props: Record<string, unknown>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </svg>
  )
}
