/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/na2GsfJnj5h
 */
import Link from "next/link"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { CardHeader, CardContent, CardFooter, Card, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function VercelExport() {
  return (
    <div key="1" className="flex flex-col min-h-screen bg-gradient-to-r from-gray-100 to-gray-200">
      <header className="px-4 py-6 bg-white flex items-center justify-between">
        <div className="text-2xl font-bold text-gray-800">Sebastian Boehler</div>
        <nav className="space-x-4">
          <Link className="text-gray-600 hover:text-gray-800" href="#">
            Portfolio
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="py-12 px-4 text-center">
          <Avatar className="mx-auto w-24 h-24">
            <AvatarImage alt="Sebastian Boehler" src="/placeholder-avatar.jpg" />
            <AvatarFallback>SB</AvatarFallback>
          </Avatar>
          <h1 className="text-3xl font-bold mt-4">Hi, I&apos;m Sebastian Boehler</h1>
          <p className="text-gray-600 mt-2">
            A 22-year-old self-taught coder currently building DeFi projects on the blockchain.
          </p>
          <Button className="mt-4">Download CV</Button>
        </section>
        <div style={{ display: 'none' }}>
          <section className="py-12 px-4" id="portfolio">
            <h2 className="text-3xl font-bold text-center">Portfolio</h2>
            <div className="space-y-6 mt-6">
              <Card className="mx-auto">
                <CardHeader>
                  <h3 className="text-lg font-bold">DeFi Project 1</h3>
                </CardHeader>
                <CardContent className="text-gray-600">
                  <p>Description of the project.</p>
                </CardContent>
                <CardFooter>
                  <Button className="mt-4" variant="secondary">
                    Learn More
                  </Button>
                </CardFooter>
              </Card>
              <Card className="mx-auto">
                <CardHeader>
                  <h3 className="text-lg font-bold">DeFi Project 2</h3>
                </CardHeader>
                <CardContent className="text-gray-600">
                  <p>Description of the project.</p>
                </CardContent>
                <CardFooter>
                  <Button className="mt-4" variant="secondary">
                    Learn More
                  </Button>
                </CardFooter>
              </Card>
              <Button className="mt-4 mx-auto">View More Projects</Button>
            </div>
          </section>
          <section className="py-12 px-4 bg-gray-50" id="skills">
            <h2 className="text-3xl font-bold text-center">Skills</h2>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-6 mt-6">
              <Badge className="justify-self-center">JavaScript</Badge>
              <Badge className="justify-self-center">Solidity</Badge>
              <Badge className="justify-self-center">React</Badge>
              <Badge className="justify-self-center">Node.js</Badge>
              <Badge className="justify-self-center">Ethereum</Badge>
              <Badge className="justify-self-center">Smart Contracts</Badge>
            </div>
          </section>
          <section className="py-12 px-4" id="social">
            <h2 className="text-3xl font-bold text-center">Follow Me</h2>
            <div className="flex justify-center space-x-4 mt-6">
              <Button className="mx-auto">
                <YoutubeIcon className="w-4 h-4 mr-2" />
                YouTube
              </Button>
              <Button className="mx-auto">
                <GithubIcon className="w-4 h-4 mr-2" />
                GitHub
              </Button>
              <Button className="mx-auto">
                <TwitterIcon className="w-4 h-4 mr-2" />
                Twitter
              </Button>
              <Button className="mx-auto">
                <FacebookIcon className="w-4 h-4 mr-2" />
                Facebook
              </Button>
              <Button className="mx-auto">
                <InstagramIcon className="w-4 h-4 mr-2" />
                Instagram
              </Button>
            </div>
          </section>
        </div>
        <section className="py-12 px-4">
          <h2 className="text-3xl font-bold text-center">Contact</h2>
          <Card className="mx-auto mt-6 w-3/4 lg:w-1/2">
            <CardHeader>
              <CardTitle>Let&apos;s Chat</CardTitle>
              <CardDescription>Interested in working together? Fill out the form below.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" type="email" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="message">Message</Label>
                <Textarea className="min-h-[100px]" id="message" placeholder="Enter your message" />
              </div>
            </CardContent>
            <CardFooter>
              <Button>Send Message</Button>
            </CardFooter>
          </Card>
        </section>
      </main>
      <footer className="py-6 bg-white text-center">
        <p className="text-gray-600">© Sebastian Boehler. All rights reserved.</p>
      </footer>
    </div>
  )
}


function YoutubeIcon(props: Record<string, unknown>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}


function GithubIcon(props: Record<string, unknown>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function TwitterIcon(props: Record<string, unknown>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function FacebookIcon(props: Record<string, unknown>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props: Record<string, unknown>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}
